### ISSUE TITLE
Software does not build with any available gcc versions

### ISSUE THREAD

**Issue by jrdemasi** [pmenzel/stranded-coverage#1]
I tried to build this with gcc-4.9.2, 5.4.0, 7.1.0, and 7.2.0.  Is there a version known that actually works?  They all fail with different errors, but I'm having a hard time believing it's the compiler at this point :-) 

Also, can you support htslib not being in '../'?  Many, if not all HPC institutions have htslib bundled with samtools in a central location, but hardcoding ../ isn't really ideal.

**Comment by pmenzel** [comment]
Thanks for the bug report, it was not a compiler problem, but rather missing linker flags that are now necessary after changes in htslib.
